/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_Main */

#ifndef _Included_com_example_test_Main
#define _Included_com_example_test_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_Main
 * Method:    main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_test_Main_main
  (JNIEnv *env, jclass clazz, jobjectArray args);

#ifdef __cplusplus
}
#endif
#endif
