/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_ifk_IFKCImpl */

#ifndef _Included_com_clark_ifk_IFKCImpl
#define _Included_com_clark_ifk_IFKCImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    register
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    unregister
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_unregister
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    rm
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_rm
  (JNIEnv *, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    m
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_m
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    rmrm
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_rmrm
  (JNIEnv *, jobject, jobject, jstring, jobject, jstring, jobjectArray);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    rmm
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_rmm
  (JNIEnv *, jobject, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    mrm
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_mrm
  (JNIEnv *, jobject, jstring, jobject, jstring, jobjectArray);

/*
 * Class:     com_clark_ifk_IFKCImpl
 * Method:    mm
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_ifk_IFKCImpl_mm
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
