/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_app_MainActivity */

#ifndef _Included_com_clark_app_MainActivity
#define _Included_com_clark_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_clark_app_MainActivity
     * Method:    test
     * Signature: ()Ljava/lang/Object;
     */JNIEXPORT jobject JNICALL Java_com_clark_app_MainActivity_test(JNIEnv *,
            jobject);

#ifdef __cplusplus
}
#endif
#endif
