/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coms_Vm */

#ifndef _Included_coms_Vm
#define _Included_coms_Vm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coms_Vm
 * Method:    fatalError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_coms_Vm_fatalError
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coms_Vm
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_coms_Vm_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     coms_Vm
 * Method:    fromReflectedField
 * Signature: (Ljava/lang/reflect/Field;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_fromReflectedField
  (JNIEnv *, jclass, jobject);

/*
 * Class:     coms_Vm
 * Method:    fromReflectedMethod
 * Signature: (Ljava/lang/reflect/Method;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_fromReflectedMethod
  (JNIEnv *, jclass, jobject);

/*
 * Class:     coms_Vm
 * Method:    toReflectedField
 * Signature: (Ljava/lang/Class;JZ)Ljava/lang/reflect/Field;
 */
JNIEXPORT jobject JNICALL Java_coms_Vm_toReflectedField
  (JNIEnv *, jclass, jclass, jlong, jboolean);

/*
 * Class:     coms_Vm
 * Method:    toReflectedMethod
 * Signature: (Ljava/lang/Class;JZ)Ljava/lang/reflect/Method;
 */
JNIEXPORT jobject JNICALL Java_coms_Vm_toReflectedMethod
  (JNIEnv *, jclass, jclass, jlong, jboolean);

/*
 * Class:     coms_Vm
 * Method:    getMethodId
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_getMethodId
  (JNIEnv *, jclass, jclass, jstring, jstring);

/*
 * Class:     coms_Vm
 * Method:    getFieldId
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_getFieldId
  (JNIEnv *, jclass, jclass, jstring, jstring);

/*
 * Class:     coms_Vm
 * Method:    getStaticMethodId
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_getStaticMethodId
  (JNIEnv *, jclass, jclass, jstring, jstring);

/*
 * Class:     coms_Vm
 * Method:    getStaticFieldId
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_coms_Vm_getStaticFieldId
  (JNIEnv *, jclass, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
