/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_app_JStringTester */

#ifndef _Included_com_clark_app_JStringTester
#define _Included_com_clark_app_JStringTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clark_app_JStringTester
 * Method:    main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_clark_app_JStringTester_main(JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
