/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sina_weibosdk_parser_JsonParser */

#ifndef _Included_com_sina_weibosdk_parser_JsonParser
#define _Included_com_sina_weibosdk_parser_JsonParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserGeo
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/Geo;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserGeo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserMessage
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/Message;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserMessageList
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/MessageList;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserMessageList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserStatus
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/Status;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserStatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserStatusList
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/StatusList;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserStatusList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_weibosdk_parser_JsonParser
 * Method:    parserUserInfo
 * Signature: (Ljava/lang/String;)Lcom/sina/weibosdk/entity/UserInfo;
 */
JNIEXPORT jobject JNICALL Java_com_sina_weibosdk_parser_JsonParser_parserUserInfo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
